#!/bin/bash

# Installation des dépendances
sudo apt install ca-certificates curl gnupg lsb-release

# Configuration des sources APT Docker
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Mise à jour des paquets APT et installation de Docker
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io docker-compose

# Vérification de l'état de Docker et ajout d'un utilisateur au groupe Docker
sudo systemctl is-enabled docker
sudo systemctl status docker
sudo adduser grp2
sudo usermod -aG docker grp2

# Téléchargement des images Docker Guacamole et Postgres
docker pull guacamole/guacd
docker pull guacamole/guacamole
docker pull postgres:13

# Création du répertoire pour le serveur Guacamole et initialisation de la base de données
mkdir -p guacamole-server; cd guacamole-server/
mkdir -p init
touch docker-compose.yml

docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > init/initdb.sql

# Configuration de docker-compose.yml pour les services Guacamole, guacd et Postgres

# Exécution du service Guacamole via Docker Compose
docker compose up -d
docker compose ps

# Installation et configuration de Nginx avec certbot pour la gestion des certificats SSL
sudo apt install nginx certbot python3-certbot-nginx

# Configuration du pare-feu UFW pour autoriser le trafic SSH et HTTP(S)
sudo ufw allow OpenSSH
sudo ufw allow 'Nginx Full'
sudo ufw enable
sudo ufw status

# Configuration de Nginx pour le service Guacamole
sudo nano /etc/nginx/sites-available/guacamole.conf

# Création d'un lien symbolique et redémarrage de Nginx
sudo ln -s /etc/nginx/sites-available/guacamole.conf /etc/nginx/sites-enabled/
sudo nginx -t
sudo systemctl restart nginx

# Génération et installation du certificat SSL avec Certbot
sudo certbot --nginx --agree-tos --redirect --hsts --staple-ocsp --email grp2@hdevops.io -d guacamole.hwdomain.io

# Affichage des informations pour se connecter à Guacamole
echo "Votre identifiant Guacamole est : guacuser"
echo "Votre mot de passe Guacamole est : $(grep 'guacuser' /var/lib/guacamole/guacamole-auth/*.xml | sed 's/.*<password>\(.*\)<\/password>.*/\1/')"
echo "Vous pouvez accéder à Guacamole via l'adresse IP de votre serveur et le port 8181 (http://<adresse_IP>:8181/guacamole/)"
